### ISSUE TITLE
Chrome prod: 'offscreen' requires canary channel or newer, but this is the stable channel.

### ISSUE THREAD

**Issue by WellRedPandit** [gildas-lormeau/SingleFile-Lite#10]
**Describe the bug**
Not sure if it's a bug at all or a feature :) Mostly an FYI I guess...

When I `Load unpacked` SingleFile-Lite in prod Chrome (the latest version, 107.0.5304.110), it says in the Errors page

> ` 'offscreen' requires canary channel or newer, but this is the stable channel.`

I've tested in Canary or Chromium and no such message is emitted.

**Screenshot:**

<img width="664" alt="image" src="https://user-images.githubusercontent.com/3659381/201488079-c865d939-3386-4024-a9ac-0f5f69eb9631.png">

P.S. I'm slowly switching to SingleFile-Lite as V2 is going away... Thank you so much for porting SingleFile to Manifest V3!

**Comment by gildas-lormeau** [comment]
Thank you :) I confirm this warning is normal. The `offscren` permission is very recent and is not available in the stable version of Chrome yet. I wanted to use it ASAP in order to validate that it would fix the auto-save feature in SingleFile Lite.

Although, this warning does not prevent SingleFile Lite to work as long as you don't use the auto-save feature.

**Comment by gildas-lormeau** [comment]
I think I can close this issue now :)
